codecov:
  branch: master
  bot: lock8-admin

comment:
  layout: header, changes, diff, sunburst

coverage:
  precision: 2
  round: down
  range: "70..100"

  status:
    project:
      default:
        target: auto
        threshold: null
        branches: null

    patch:
      default:
        target: 100
        branches: null

    changes:
      default:
        branches: null

  flags:
    default:
      ignore:
        - velodrome/lock8/migrations/*
        - velodrome/advanced_devices/migrations/*
        - velodrome/custom_tagging/migrations/*
        - velodrome/features_flags/migrations/*
  ignore: null

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
