# -*- coding: utf-8 -*-
# Generated by Django 1.11.3.dev20170628143432 on 2017-06-28 14:59
from __future__ import unicode_literals

from django.db import migrations

from velodrome.lock8 import migration_utils


def create_owner(apps, schema_editor):
    User = apps.get_model('lock8', 'User')
    User.objects.get_or_create(username='root_admin',
                               email='development@lock8.me')


def create_root_org(apps, schema_editor):
    Organization = apps.get_model('lock8', 'Organization')
    if Organization.objects.filter(level=0).exists():
        return
    User = apps.get_model('lock8', 'User')
    admin = User.objects.get(username='root_admin')
    migration_utils.create_root_org(Organization, admin)


def create_default_site(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Site.objects.get_or_create(domain='lock8.me', name='api')


def create_bicycle_types(apps, schema_editor):
    User = apps.get_model('lock8', 'User')
    BicycleType = apps.get_model('lock8', 'BicycleType')
    admin = User.objects.get(username='root_admin')
    migration_utils.create_bicycle_types(BicycleType, admin)


def create_root_feedback_categories(apps, schema_editor):
    Organization = apps.get_model('lock8', 'Organization')
    FeedbackCategory = apps.get_model('lock8', 'FeedbackCategory')
    migration_utils.create_root_feedback_categories(Organization, FeedbackCategory)


def create_default_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Debug')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lock8', '0002_initial_models'),
    ]

    operations = [
        migrations.RunPython(create_owner,
                             reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_root_org,
                             reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_default_site,
                             reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_root_feedback_categories,
                             reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_default_groups,
                             reverse_code=migrations.RunPython.noop),
        migrations.RunPython(create_bicycle_types,
                             reverse_code=migrations.RunPython.noop),
    ]
