# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0003_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpreference',
            name='is_free_floating_fleet',
            field=models.BooleanField(default=False, help_text='Is the organization running a pure free floating fleet? A free floating fleet contains only bicycles without locks. If True, the rider app will not display the button inviting renters to scan the QR code of the bicycle.'),
        ),
    ]
