# -*- coding: utf-8 -*-
# Generated by Django 1.11.4.dev20170707110142 on 2017-07-07 11:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0006_migrate_amount_to_cents_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatetracking',
            name='bicycle',
        ),
        migrations.RemoveField(
            model_name='privatetracking',
            name='lock',
        ),
        migrations.RemoveField(
            model_name='privatetracking',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='publictracking',
            name='bicycle',
        ),
        migrations.RemoveField(
            model_name='publictracking',
            name='lock',
        ),
        migrations.RemoveField(
            model_name='publictracking',
            name='organization',
        ),
    ]
