# -*- coding: utf-8 -*-
# Generated by Django 1.11.4.dev20170721222603 on 2017-07-25 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0008_organizationpreference_support_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpreference',
            name='is_access_controlled',
            field=models.BooleanField(default=True, help_text='Does the organization use access control (i.e. locks)?'),
        ),
        migrations.AlterField(
            model_name='organizationpreference',
            name='is_free_floating_fleet',
            field=models.BooleanField(default=False, help_text='Deprecated.'),
        ),
    ]
