# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170807133843 on 2017-08-29 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0009_auto_20170725_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='interval',
            field=models.CharField(choices=[('day', 'day'), ('week', 'week'), ('month', 'month'), ('year', 'year')], max_length=10),
        ),
    ]
