# -*- coding: utf-8 -*-
# Generated by Django 1.11.5.dev20170807133843 on 2017-09-04 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0010_auto_20170829_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpreference',
            name='support_phone_number',
            field=models.CharField(blank=True, help_text='Primary support phone number.', max_length=128, null=True),
        ),
    ]
