# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-05 15:06
from __future__ import unicode_literals

from django.contrib.postgres.operations import (
    TrigramExtension, UnaccentExtension,
)
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0011_organizationpreference_support_phone_number'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
    ]
