# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-09-14 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0013_add_support_tickets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizationpreference',
            old_name='allow_renting_without_pricing_scheme',
            new_name='allow_renting_without_pricings',
        ),
    ]
