# -*- coding: utf-8 -*-
# Generated by Django 1.11.6.dev20170907100046 on 2017-09-14 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0014_rename_allow_renting_without_pricing_scheme'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER TABLE lock8_organization ADD CONSTRAINT single_tree_id CHECK (tree_id = 1)',
            reverse_sql='ALTER TABLE lock8_organization DROP CONSTRAINT single_tree_id',
        ),
    ]
