# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-09-29 10:31
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0016_add_payment_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientapp',
            name='scopes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bicycle:read', 'bicycle:read'), ('bicycle:write', 'bicycle:write'), ('organization:read', 'organization:read'), ('trip:read', 'trip:read')], max_length=64), blank=True, default=list, size=None),
        ),
    ]
