# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-09-29 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0017_increase-scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientapp',
            name='label',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
