# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-09-29 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0018_client-app-label'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clientapp',
            unique_together=set([('name', 'organization')]),
        ),
    ]
