# -*- coding: utf-8 -*-
# Generated by Django 1.11.6.dev20170907100046 on 2017-09-29 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0019_client-app-unique-name-org'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'get_latest_by': 'modified', 'ordering': ('-modified', '-created')},
        ),
    ]
