# -*- coding: utf-8 -*-
# Generated by Django 1.11.6.dev20170907100046 on 2017-10-02 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0020_auto_20170929_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingscheme',
            name='max_daily_charged_amount',
        ),
        migrations.RemoveField(
            model_name='rentalsession',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='amount',
        ),
    ]
