# -*- coding: utf-8 -*-
# Generated by Django 1.11.6.dev20170907100046 on 2017-10-04 14:52
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0021_auto_20171002_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('renter', 'Renter'), ('fleet_operator', 'Fleet Operator'), ('admin', 'Admin'), ('mechanic', 'Mechanic'), ('security', 'Security'), ('spectator', 'Spectator'), ('production_software', 'Production Software')], max_length=25), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='axalock',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='bicyclemetadata',
            name='needs_attention_score',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='bicyclemetadata',
            name='recoverability_score',
            field=models.IntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='privatetracking',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='publictracking',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='rentalsession',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'U.S. Dollars'), ('gbp', 'Pounds (GBP)'), ('eur', 'Euros')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
    ]
