# -*- coding: utf-8 -*-
# Generated by Django 1.11.6.dev20170907100046 on 2017-10-12 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0022_auto_20171004_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='cents',
            field=models.IntegerField(default=0, verbose_name='Amount (per period) in cents'),
            preserve_default=False,
        ),
    ]
