# -*- coding: utf-8 -*-
# Generated by Django 1.11.6.dev20170907100046 on 2017-10-13 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0023_auto_20171012_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpreference',
            name='uses_payments',
            field=models.BooleanField(default=False, help_text='Does the organization/fleet uses payments?'),
        ),
    ]
