# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-17 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pinax_stripe', '0010_connect_squashed_0026_merge_20171106_2259'),
        ('lock8', '0024_organizationpreference_uses_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stripe_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinax_stripe.Account'),
        ),
    ]
