# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0025_organization-account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationpreference',
            name='uses_payments',
        ),
    ]
