# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 14:23
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import velodrome.lock8.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0026_remove-org-pref-uses_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingscheme',
            name='description',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Dictionary of localized pricing scheme descriptions.', validators=[velodrome.lock8.validators.validate_payment_description]),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='description',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, help_text='Dictionary of localized subscription plan descriptions.', validators=[velodrome.lock8.validators.validate_payment_description]),
        ),
    ]
