# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0029_auto_20171024_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicyclemodel',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Visible only to fleet operators.'),
        ),
    ]
