# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0030_add_bicycle_model_hidden_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='category',
            field=models.CharField(blank=True, choices=[('location_needs_bicycles', 'Bicycles requested by a rider'), ('bicycle_missing', "Rider couldn't find a bicycle"), ('bicycle_damaged', 'Rider reported a damaged bicycle')], max_length=25, null=True),
        ),
    ]
