# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-11-23 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0033_restricted_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='White Label users can belong to only one organization.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to='lock8.Organization'),
        ),
    ]
