# -*- coding: utf-8 -*-
# Generated by Django 1.11.8.dev20171122101223 on 2017-12-01 16:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import velodrome.lock8.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0035_auto_20171123_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricingscheme',
            name='description',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Dictionary of localized pricing scheme descriptions, e.g. {"en": {"title": "Title", "description": "Description", "short_description": "Short", "fine_print": "Fine print"}}', validators=[velodrome.lock8.validators.validate_payment_description]),
        ),
        migrations.AlterField(
            model_name='pricingscheme',
            name='time_ranges',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, help_text='A list of time ranges (lower_duration, upper_duration, cents, prorated, prorated_duration), e.g. [[0, null, 500, false, null]]', validators=[velodrome.lock8.validators.validate_time_ranges]),
        ),
    ]
