# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 08:46
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0038_accepted_tos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography=True, srid=4326),
        ),
    ]
