# Generated by Django 2.0.1 on 2018-01-12 13:04

from django.db import migrations, models


def set_default_root_org_values(apps, schema_editor):
    from velodrome.lock8.migration_utils import set_root_org_values
    Organization = apps.get_model('lock8', 'Organization')
    OrganizationPreference = apps.get_model('lock8', 'OrganizationPreference')
    User = apps.get_model('lock8', 'User')

    root_org = Organization.objects.get(parent=None, tree_id=1)
    root_admin, _ = User.objects.get_or_create(
        username='root_admin',
        email='development@lock8.me')
    set_root_org_values(root_org, root_admin, OrganizationPreference)


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0040_auto_20180112_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='app_download_url',
            field=models.URLField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_whitelabel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='user_email_logo',
            field=models.ImageField(blank=True, max_length=254, upload_to='user_email_logo'),
        ),
        migrations.RunPython(
            set_default_root_org_values, reverse_code=migrations.RunPython.noop),
    ]
