# Generated by Django 2.0.1 on 2018-01-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0041_org_user_email_template'),
        ('lock8', '0041_sts-lock-write'),
    ]

    operations = [
    ]
