# Generated by Django 2.0.3.dev20180212144320 on 2018-02-19 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0043_auto_20180207_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='White Label users can belong to only one organization.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='whitelabel_members', related_query_name='whitelabel_member', to='lock8.Organization'),
        ),
    ]
