# Generated by Django 2.0.3.dev20180227010029 on 2018-02-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0045_auto_20180222_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='is_maintenance',
        ),
    ]
