# Generated by Django 2.0.2 on 2018-03-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0048_auto_20180309_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='description',
            field=models.TextField(blank=True, default=None, help_text='Meaning of custom zone.', null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='type',
            field=models.CharField(choices=[('dropzone', 'Dropzone'), ('cycling_area', 'Service Area'), ('maintenance', 'Maintenance'), ('custom', 'Custom')], default='dropzone', max_length=12),
        ),
    ]
