# Generated by Django 2.0.3.dev20180302194802 on 2018-03-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0049_zone_custom_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalsession',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'U.S. Dollars'), ('gbp', 'Pounds (GBP)'), ('eur', 'Euros')], max_length=10, null=True),
        ),
    ]
