# Generated by Django 2.0.6 on 2018-06-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0054_failed_payment_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalsession',
            name='duration_of_rental_session',
            field=models.DurationField(blank=True, db_column='duration_of_rental_session', default=None, null=True),
        ),
        migrations.RenameField(
            model_name='rentalsession',
            old_name='duration_of_rental_session',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.URLField(blank=True, max_length=254, null=True),
        ),
    ]
