# Generated by Django 2.0.13 on 2019-06-16 19:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0060_auto_20190513_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientapp',
            name='scopes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('bicycle:read', 'bicycle:read'), ('bicycle:write', 'bicycle:write'), ('lock:write', 'lock:write'), ('organization:read', 'organization:read'), ('support-ticket:read', 'support-ticket:read'), ('support-ticket:write', 'support-ticket:write'), ('trip:read', 'trip:read'), ('zone:read', 'zone:read'), ('zone:write', 'zone:write')], max_length=64), blank=True, default=list, size=None),
        ),
    ]
