# Generated by Django 2.0.13 on 2020-06-05 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0061_auto_20190616_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='AxaLockConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paired', models.DateTimeField(auto_now_add=True)),
                ('detached', models.DateTimeField(blank=True, null=True)),
                ('axa_lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axa_lock_connections', related_query_name='axa_lock_connection', to='lock8.AxaLock')),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axa_lock_connections', related_query_name='axa_lock_connection', to='lock8.Bicycle')),
            ],
        ),
        migrations.CreateModel(
            name='LockConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paired', models.DateTimeField(auto_now_add=True)),
                ('detached', models.DateTimeField(blank=True, null=True)),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lock_connections', related_query_name='lock_connection', to='lock8.Bicycle')),
                ('lock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lock_connections', related_query_name='lock_connection', to='lock8.Lock')),
            ],
        ),
        migrations.AddIndex(
            model_name='lockconnection',
            index=models.Index(fields=['-paired'], name='lock8_lockc_paired_3e3a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='lockconnection',
            index=models.Index(fields=['-detached'], name='lock8_lockc_detache_8f792b_idx'),
        ),
        migrations.AddIndex(
            model_name='axalockconnection',
            index=models.Index(fields=['-paired'], name='lock8_axalo_paired_e5e813_idx'),
        ),
        migrations.AddIndex(
            model_name='axalockconnection',
            index=models.Index(fields=['-detached'], name='lock8_axalo_detache_c114cd_idx'),
        ),
    ]
