# Generated by Django 2.0.13 on 2020-12-17 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0063_bicycle_note'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bicycle',
            unique_together={('organization', 'name')},
        ),
    ]
