# Generated by Django 2.0.13 on 2021-03-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0064_bicycle_unique_org_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='high_threshold',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='High threshold'),
        ),
        migrations.AddField(
            model_name='zone',
            name='low_threshold',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Low threshold'),
        ),
    ]
