# Generated by Django 2.0.13 on 2021-04-07 12:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0066_zone_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='role',
            field=models.CharField(choices=[('renter', 'Renter'), ('fleet_operator', 'Fleet Operator'), ('admin', 'Admin'), ('mechanic', 'Mechanic'), ('security', 'Security'), ('spectator', 'Spectator'), ('production_software', 'Production Software'), ('supervisor', 'Supervisor')], default='renter', max_length=25),
        ),
        migrations.AlterField(
            model_name='alert',
            name='role',
            field=models.CharField(blank=True, choices=[('renter', 'Renter'), ('fleet_operator', 'Fleet Operator'), ('admin', 'Admin'), ('mechanic', 'Mechanic'), ('security', 'Security'), ('spectator', 'Spectator'), ('production_software', 'Production Software'), ('supervisor', 'Supervisor')], max_length=25),
        ),
        migrations.AlterField(
            model_name='alert',
            name='roles',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('renter', 'Renter'), ('fleet_operator', 'Fleet Operator'), ('admin', 'Admin'), ('mechanic', 'Mechanic'), ('security', 'Security'), ('spectator', 'Spectator'), ('production_software', 'Production Software'), ('supervisor', 'Supervisor')], max_length=25), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='bicyclemodelmaintenancerule',
            name='role',
            field=models.CharField(choices=[('renter', 'Renter'), ('fleet_operator', 'Fleet Operator'), ('admin', 'Admin'), ('mechanic', 'Mechanic'), ('security', 'Security'), ('spectator', 'Spectator'), ('production_software', 'Production Software'), ('supervisor', 'Supervisor')], default='mechanic', max_length=25),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('renter', 'Renter'), ('fleet_operator', 'Fleet Operator'), ('admin', 'Admin'), ('mechanic', 'Mechanic'), ('security', 'Security'), ('spectator', 'Spectator'), ('production_software', 'Production Software'), ('supervisor', 'Supervisor')], default='renter', max_length=25),
        ),
        migrations.AlterField(
            model_name='task',
            name='role',
            field=models.CharField(choices=[('renter', 'Renter'), ('fleet_operator', 'Fleet Operator'), ('admin', 'Admin'), ('mechanic', 'Mechanic'), ('security', 'Security'), ('spectator', 'Spectator'), ('production_software', 'Production Software'), ('supervisor', 'Supervisor')], default='mechanic', max_length=25),
        ),
    ]
