# Generated by Django 2.2.14 on 2021-03-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0068_django_upgrade_20_to_22'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acceptedtermsofservice',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'get_latest_by': 'modified', 'ordering': ('-created',), 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='affiliation',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='alertmessage',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='axalock',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='bicycle',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='bicyclemetadata',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='bicyclemodel',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='bicyclemodelmaintenancerule',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='bicycletype',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='clientapp',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='feedbackcategory',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='firmware',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='invitation',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='lock',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='lockfirmwareupdate',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='notificationmessage',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='organizationpreference',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='planpass',
            options={'get_latest_by': 'modified', 'ordering': ('-created',), 'verbose_name_plural': 'plan passes'},
        ),
        migrations.AlterModelOptions(
            name='pricingscheme',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='rentalsession',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='rentingscheme',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='sharedsecret',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='supportticket',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='termsofservice',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='termsofserviceversion',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'get_latest_by': 'modified', 'ordering': ('-created',), 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
    ]
