# Generated by Django 2.2.28 on 2022-08-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0073_auto_20220819_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle',
            name='locked',
            field=models.BooleanField(default=True),
        ),
    ]
