# Generated by Django 2.2.28 on 2022-08-20 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0074_bicycle_locked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicyclemodel',
            name='locked',
        ),
    ]
