# Generated by Django 2.2.28 on 2022-08-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0073_auto_20220822_1353'),
        ('lock8', '0075_remove_bicyclemodel_locked'),
    ]

    operations = [
    ]
