# Generated by Django 2.0.13 on 2021-03-03 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lock8', '0063_bicycle_note'),
        ('advanced_devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfigContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('device_type', models.IntegerField(choices=[(1, 'DISPENSER')], db_index=True, verbose_name='Device type')),
                ('content', models.TextField(default='', verbose_name='Content')),
                ('devices', models.ManyToManyField(blank=True, db_table='velodrome_adv_device_with_config', related_name='config_records', to='advanced_devices.DeviceModel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adv_device_config_list', related_query_name='adv_device_config_list', to='lock8.Organization', verbose_name='Organization')),
            ],
            options={
                'verbose_name': 'Advanced devices config content',
                'db_table': 'velodrome_adv_device_config',
                'ordering': ['-updated'],
            },
        ),
    ]
