# Generated by Django 2.0.13 on 2021-04-08 15:57

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_devices', '0003_add_supervisor_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStreamSampleModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='pk')),
                ('created', models.DateTimeField(verbose_name='Created at client')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('data_type', models.IntegerField(choices=[(0, 'UNKNOWN'), (1, 'DEBUG_SENSOR_EVENT_VALID'), (2, 'DEBUG_SENSOR_EVENT_INVALID')], db_index=True, verbose_name='Content type')),
                ('sample', models.IntegerField(default=0, verbose_name='Sample')),
                ('quantum', models.FloatField(default=0, verbose_name='Quantum (ms)')),
                ('index_position', django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Position metadata')),
                ('values', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[], size=None, verbose_name='Stream values')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_samples', related_query_name='stream_samples', to='advanced_devices.DeviceModel', verbose_name='Device')),
            ],
            options={
                'verbose_name': 'Device data stream sample',
                'db_table': 'velodrome_adv_device_data_stream',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='deviceconfigcontentmodel',
            name='content',
            field=models.TextField(default='', verbose_name='Content (ini)'),
        ),
    ]
