# Generated by Django 2.0.13 on 2021-04-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_devices', '0004_create_datastream'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastreamsamplemodel',
            name='status',
            field=models.IntegerField(choices=[(1, 'NEW'), (2, 'VALID'), (3, 'INVALID')], default=1, verbose_name='Status'),
        ),
    ]
