# Generated by Django 2.2.14 on 2021-03-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_devices', '0005_datastreamsamplemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfigcontentmodel',
            name='content',
            field=models.TextField(default='', verbose_name='Content (ini)'),
        ),
    ]
