# Generated by Django 2.2.14 on 2021-03-23 20:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_devices', '0006_alter_content_field_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatemodel',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Attributes'),
        ),
    ]
