# Generated by Django 2.2.14 on 2021-04-26 11:41

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_devices', '0007_fix_jsonfield_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastreamsamplemodel',
            name='index_position',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Position metadata'),
        ),
        migrations.AlterField(
            model_name='datastreamsamplemodel',
            name='values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, size=None, verbose_name='Stream values'),
        ),
    ]
