# Generated by Django 2.2.14 on 2021-06-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_devices', '0009_auto_20210602_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicetypemodel',
            name='key_format',
            field=models.IntegerField(choices=[(1, 'sanitizer-NNN'), (2, 'soap-NNN')], default=1, verbose_name='Unique key format'),
        ),
    ]
