# Generated by Django 2.2.14 on 2021-06-09 10:07

from django.db import migrations


def clear_types_table(apps, *args):
    device_cls = apps.get_model("advanced_devices", "DeviceModel")
    manager = getattr(
        device_cls.objects, "no_organizations", device_cls.objects.all
    )
    all_devices = manager().all()
    if all_devices.count() > 0:
        # to save records in db
        all_devices.update(device_model=None)

    type_cls = apps.get_model("advanced_devices", "DeviceTypeModel")
    type_cls.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("advanced_devices", "0010_devicetypemodel_key_format"),
    ]

    operations = [
        migrations.RunPython(clear_types_table),
    ]
