# Generated by Django 2.2.14 on 2021-06-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_devices', '0011_auto_20210609_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetypemodel',
            name='key_format',
        ),
        migrations.AddField(
            model_name='devicetypemodel',
            name='unique_key',
            field=models.CharField(default='', max_length=36, unique=True, verbose_name='Unique key'),
        ),
    ]
