# Generated by Django 2.2.14 on 2021-06-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_devices', '0012_auto_20210609_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceconfigcontentmodel',
            name='device_type',
            field=models.IntegerField(choices=[(1, 'DISPENSER'), (2, 'SOAP_DISPENSER')], db_index=True, verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='devicemodel',
            name='device_type',
            field=models.IntegerField(choices=[(1, 'DISPENSER'), (2, 'SOAP_DISPENSER')], db_index=True, verbose_name='Device base type/group'),
        ),
        migrations.AlterField(
            model_name='devicetypemodel',
            name='device_type',
            field=models.IntegerField(choices=[(1, 'DISPENSER'), (2, 'SOAP_DISPENSER')], verbose_name='Type'),
        ),
    ]
