# Generated by Django 2.2.28 on 2022-05-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advanced_devices', '0013_auto_20210610_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicestatemodel',
            name='state_type',
            field=models.IntegerField(choices=[(1, 'LOCATION_CHANGED'), (2, 'BATTERY_STATUS'), (3, 'FLUID_STATUS'), (4, 'FIRMWARE_AVAILABLE'), (5, 'FIRMWARE_INSTALLED'), (6, 'DISPLAY_STATUS'), (7, 'SERVICED'), (8, 'AMBIENT_STATE')], verbose_name='State type'),
        ),
    ]
