# Generated by Django 2.2.14 on 2021-03-22 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_tagging', '0002_tagdeclaration_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagdeclaration',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='taggroup',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='taginstance',
            options={'get_latest_by': 'modified', 'ordering': ('-created',)},
        ),
    ]
